# Generated by Django 5.2.14 on 2026-05-11 04:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('cpu', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=255)),
                ('gb_ram', models.IntegerField()),
                ('storage_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hardware',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'videogame',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('benchmark_type', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.FloatField()),
                ('fps_avg', models.FloatField(blank=True, null=True)),
                ('fps_min', models.IntegerField(blank=True, null=True)),
                ('fps_max', models.IntegerField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('settings', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hardware')),
            ],
            options={
                'db_table': 'result',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='hardware',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fps_min', models.IntegerField(blank=True, null=True)),
                ('fps_max', models.IntegerField(blank=True, null=True)),
                ('fps_avg', models.FloatField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('settings', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hardware')),
                ('video_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.videogame')),
            ],
            options={
                'db_table': 'game_result',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VideogameRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=255)),
                ('gb_ram', models.IntegerField(blank=True, null=True)),
                ('target_fps', models.IntegerField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('settings', models.CharField(blank=True, max_length=100, null=True)),
                ('video_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.videogame')),
            ],
            options={
                'db_table': 'videogame_requirement',
                'managed': True,
            },
        ),
    ]
