# Generated by Django 5.2.14 on 2026-06-09 23:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('base_specs', models.TextField(blank=True)),
                ('launch_year', models.IntegerField(blank=True, null=True)),
                ('base_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hardware_component',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BenchmarkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('cpu_avg', models.FloatField()),
                ('cpu_max', models.FloatField()),
                ('cpu_temp_avg', models.FloatField(blank=True, null=True)),
                ('cpu_temp_max', models.FloatField(blank=True, null=True)),
                ('gpu_avg', models.FloatField()),
                ('gpu_max', models.FloatField()),
                ('gpu_temp_avg', models.FloatField(blank=True, null=True)),
                ('gpu_temp_max', models.FloatField(blank=True, null=True)),
                ('ram_avg_gb', models.FloatField()),
                ('ram_max_gb', models.FloatField()),
                ('disk_read_avg', models.FloatField(blank=True, null=True)),
                ('disk_write_avg', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hardware', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hardware')),
            ],
            options={
                'db_table': 'benchmark_session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SessionSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_seconds', models.IntegerField()),
                ('cpu_pct', models.FloatField()),
                ('gpu_pct', models.FloatField()),
                ('ram_gb', models.FloatField()),
                ('cpu_temp', models.FloatField(blank=True, null=True)),
                ('gpu_temp', models.FloatField(blank=True, null=True)),
                ('disk_read', models.FloatField(blank=True, null=True)),
                ('disk_write', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.benchmarksession')),
            ],
            options={
                'db_table': 'session_sample',
                'ordering': ['timestamp_seconds'],
                'managed': True,
            },
        ),
    ]
