# Generated by Django 5.2.14 on 2026-07-07 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hardwarecomponent_benchmarksession_sessionsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpu_avg', models.FloatField(blank=True, null=True)),
                ('cpu_max', models.FloatField(blank=True, null=True)),
                ('gpu_avg', models.FloatField(blank=True, null=True)),
                ('gpu_max', models.FloatField(blank=True, null=True)),
                ('ram_avg_gb', models.FloatField(blank=True, null=True)),
                ('ram_max_gb', models.FloatField(blank=True, null=True)),
                ('fps_avg', models.FloatField(blank=True, null=True)),
                ('fps_max', models.FloatField(blank=True, null=True)),
                ('fps_min', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FPSSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fps', models.FloatField()),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('gpu_usage', models.FloatField(blank=True, null=True)),
                ('ram_usage_gb', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.fpssession')),
            ],
        ),
    ]
